apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-app
  namespace: argocd
spec:
  description: Production GitOps project for demo-app

  sourceRepos:
    - https://github.com/muralidhargurram39/production-eks-platform.git

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
