replicaCount: 3

image:
  repository: 438064565553.dkr.ecr.ap-south-2.amazonaws.com/demo-app
  tag: "b5b237d6bfaac13813ade767676caae15d8505a2"
  pullPolicy: Always

podLabels:
  app.kubernetes.io/environment: dev

ingress:
  enabled: true
  host: dev.muralidharops.com

networkPolicy:
  enabled: true
  ingress:
    namespaceSelector:
      matchLabels:
        environment: dev
    port: 8080

podDisruptionBudget:
  enabled: true
  minAvailable: 2
