apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-gp3-test-pvc
  namespace: storage-test
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp3

  resources:
    requests:
      storage: 5Gi
